### PR TITLE
1.11 support - DynmapCore

### PR DESCRIPTION
**Pull request by RoyCurtis**
1.9, 1.10 and 1.11 blocks supported on a DynmapBukkit render

*Above map generated from [debugging world](http://i.imgur.com/udP6prr.jpg)*

This PR attempts to implement rendering for blocks up to 1.11, including some missing in 1.9.

[There is a DynmapCoreAPI PR associated with this PR.](https://github.com/webbukkit/DynmapCoreAPI/pull/4)

# Changes

* Implements rendering of missing 1.9 blocks: beetroot, repeating & chain command blocks, frosted ice, end gateway
* Implements rendering of 1.10 blocks: magma, nether wart block, red nether brick, bone blocks, structure blocks
* Implements rendering of 1.11 blocks: observers, all shulker box colors
* Adds support for ShulkerTextureFile (shulker box maps)
* Adds the end sky texture and makes the end portals and end gateways render using that, instead of obsidian

# Testing

These commits have been tested on these servers:

* Local testing PaperSpigot server with 0 plugins, using Dynmap-Bukkit
  * `git-Paper-925 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
  * `git-Paper-956 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
* Live beta PaperSpigot server with 28 plugins, using Dynmap-Bukkit
  * ` git-Paper-928 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
* No compilation errors or runtime exceptions
* [Built JARs of this PR may be found here](https://github.com/Gamealition/DynmapCore/releases/tag/2.3-pre)

# Notes

* Figuring out rotations for texture faces on blocks was difficult for me, particularly as they seem to be incorrect (`north` appears to be `west`, `clockwise` appears to be `counterclockwise`, etc). As such, texture rotations on some blocks (e.g. shulker boxes, observers) may be incorrect in custom texture packs.
* I implemented `combineSubimageFromImage` in `TexturePack` as I could not find any other methods for *overlaying* one texture over another. However, `combineSubimageFromImage` has not been tested for efficiency or memory usage.
* I am not sure what changes are made in the files in 2b568b1; all I did was copy-paste from vanilla 1.11's jar. It looks like some of the PNGs were trimmed (e.g. file comments removed)
* ~~Still missing is proper rendering of the new 1.9 command blocks states (direction, conditional)~~

### CODE REVIEW

**Comment by Black-Hole** [comment]
This patch works fine. I just saw a small issue:
If you place a shulker box upside down the texture is mirrored and rotated in flat map.

**Comment by RoyCurtis** [comment]
Thank you for spotting that; did not test flat view

**Comment by RoyCurtis** [comment]
@Black-Hole : I could not fix that fully. Dynmap only allows for rotating OR flipping a texture, but not both. I tried to add support but it seemed to touch too many internals (e.g. OBJ export?). I am not confident enough to make and test such changes.

Instead, I fixed the rotation for flat view and the flips on isometric view. But the top-side of bottom-facing shulkers are still, for now, incorrectly flipped.

1.9+ command block support in Dynmap

In addition, I just added full support for the 1.9 command blocks. They now show their rotation and conditional state properly. [Updated JAR of bukkit plugin available here.](https://github.com/Gamealition/DynmapCore/releases/tag/2.3-pre)

**Comment by mikeprimm** [comment]
Need some time to review properly, but this looks really good.  Thanks!

BTW, the 'north' versus 'east' etc thing just shows you how old the code base is: Notch pivoted the definition of 'north' way back around 1.0, but this definition syntax is older than that...

**Comment by RoyCurtis** [comment]
No problem! I figured it might have been the old orientation...

**Comment by RoyCurtis** [comment]
Awesome! Thank you very much, mikeprimm

**Pull request merged**
