### PR TITLE
Fixes #82 webp support

### LINKED ISSUE #82: Support for WebP image format
Hello,
I'd like to ask, whether it would be possible to add a new render image format WebP. It's now widely supported by all Chromium browsers and if it would be optional as the jpg format is, it would be quite handy because we would be able to create maps in higher quality with smaller size.
I know that it's not supported by Gecko (Firefox) but it will be hopefully supported soon and it wouldn't be set as the default one.

Thank you for your response.

### PR DESCRIPTION
**Pull request by bmhm**

### CODE REVIEW

**Comment by rouing** [comment]
Does this provide a fallback for browsers that don't support the webp option? I am wondering this because I myself and 60% of my users use Firefox Quantum and Firefox Quantum Developer Edition, and while I would like to have webp, I am wondering if this is a addon to the current format or would this replace the entire format.

**Comment by bmhm** [comment]
@rouing  is this blocking the merge?

**Comment by mikeprimm** [comment]
@rouing As coded, this is a committed choice - Dynmap only renders a given map in a single image file format, so opting for 'webp' will result in the given map being rendered in that single format (and, thus, breaking anyone that has a browser that lacks support).  I'll be accepting the PR, but as I'd indicated in the conversation on the issue requesting the support (#82), it will not be a recommended nor particularly supported choice, as I don't think the improvement in the image size is justified versus the impact due to incomplete browser support - if you want smaller maps, use the existing jpeg format vs the default png format, and you'll get nearly all the size improvement.  Dynamically reencoding the webp to one of those formats isn't going to happen - it'll kill server performance, and would be a real problem for external server users (where the image files are directly served as files, versus being served via custom code), and encoding the map twice (once for webp and once for some other format) completely defeats any point in having the webp support.

**Comment by mikeprimm** [comment]
@bmhm Code is not building properly, as the com.google.webp library is not being found on the maven central repository.  Where did you get it from?  I need a supported and open source reference from a trusted source, or else I'll need to drop the merge.

**Comment by bmhm** [comment]
I have no idea anymore. It's been a while... Did you Google for it? I do not have an IDE at the moment.

**Pull request merged**
